---
abstract: 'Alias one namespace as another'
author:
  - 'Joshua Keroes <joshua@cpan.org>'
build_requires:
  Test::More: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Package-Alias
requires:
  Carp: 0
  perl: 5.006
version: 0.12
